# Generated by Django 3.2.2 on 2021-07-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='phone',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
